services:
  - type: web
    name: rookhide
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
